[customizing app 김태수]Add: views.py 작성
wecode-bootcamp-korea/11-Teslrider-backend pull request #10
Opened 2020-08-24 09:18 UTC by Blakekim93

- views.py 작성
- urls.py 작성

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
         
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-24 10:17 UTC, soheon-lee commented on customizing/views.py
> +            interior_price = Interior.objects.get(model = model_id, name = interior).price
코드를 보니 자동차의 모델과 배터리, 색, 휠, 인테리어 등을 모두 name으로 전달하시네요.
텍스트로 처리하고 계신다는 뜻이죠? 이러한 방식으로 진행하시면 한 번 요청할 때마다 6개의 테이블에 쿼리를 보내게 됩니다.
효율적인 방법이라고 할 수 없겠죠?
매 단계마다 해당하는 데이터들의 id와 이름을 뿌려주시고, 그 id 로 통신해주세요

2020-08-25 07:53 UTC, Blakekim93 commented
>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
Modify: models.py 수정    
         
## 수정 사항들 자세한 내용
- 데이터를 사전에 뿌려주는 것이 없었는데 뿌려줄 데이터를 수집하고
db저장하기 위해 models.py 수정
- interiorimages, color_wheel_images 테이블 추가

views.py에 달린 comment로 수정하기 위해서 modeling을 수정하였습니다.
views.py의 comment를 수정하는 동시에 새로운 pr을 날리도록 하겠습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-26 01:35 UTC, lordmyshepherd approved these changes

2020-08-26 01:37 UTC, lordmyshepherd requested changes

2020-08-26 01:37 UTC, lordmyshepherd commented on customizing/views.py
> +class CustomizingView(View):
태수님!! models.py commit에 다른 작업이 올라오지 않고, commit에 해당하는 작업만 올리는 연습을 부탁드려요~:+1:

2020-08-26 01:44 UTC, lordmyshepherd commented
models

2020-08-26 01:44 UTC, closed without merging