Add[문태기]: views.py 차량 데이터 전송 endpoint 구현완료
wecode-bootcamp-korea/11-Teslrider-backend pull request #9
Opened 2020-08-24 04:35 UTC by orangemush

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)
차량 데이터 전송 엔드포인트 구현       
         
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-24 06:33 UTC, soheon-lee commented on car/views.py
> +from django.shortcuts   import render
사용하지 않는 코드입니다 제거해주세요

2020-08-24 06:33 UTC, soheon-lee commented on car/views.py
> +from django.forms.models import model_to_dict
`import` 기준으로 정렬해주세요

2020-08-24 06:33 UTC, soheon-lee commented on car/views.py
> +from .models            import *
`import *`은 사용하지 않습니다. 사용하는 클래스들을 정확하게 지칭해주세요

2020-08-24 06:33 UTC, soheon-lee commented on car/views.py
> +            wheel = wheel[0]['inch'].strip()
strip() 왜 사용하신건가요? 데이터를 정리하시는 건가요?
데이터 정리는 로직에서 처리하는 과정이어서는 안됩니다. 로직을 실행하기 전 모두 정리되어 있어야 합니다. database에 넣는 과정에서 부터 정리해서 넣으시고 해당 로직은 제거해주세요

2020-08-24 06:33 UTC, soheon-lee commented on car/views.py
> +            #     wheel_list.append(wheel['inch'])
PR에 올라오는 코드는 배포용 코드이므로, 이런 사용하지 않는 주석들은 모두 제거하셔야합니다. 지워주세요

2020-08-24 06:33 UTC, soheon-lee commented on car/views.py
> +            car_specs.warranty = car_specs.warranty.replace('\n\t', "<br>")
마찬가지입니다. 데이터를 정리하시는 건가요?
데이터 정리는 로직에서 처리하는 과정이어서는 안됩니다. 로직을 실행하기 전 모두 정리되어 있어야 합니다. database에 넣는 과정에서 부터 정리해서 넣으시고 해당 로직은 제거해주세요

2020-08-24 06:33 UTC, soheon-lee commented on car/views.py
> +        #     return JsonResponse({'message': 'VALUE_ERROR'}, status = 400)
사용하지않는 주석 제거해주세요

2020-08-24 06:33 UTC, soheon-lee commented on car/views.py
> +            wheel = wheel[0]['inch'].strip()
`[0]`은 하드 코딩입니다. django에서 첫번째 객체를 호출하는 메소드가 있으니 한 번 활용해보세요. 그리고 `inch`라는 한가지 속성에만 접근하시는 것이라면 `values( )`는 사용할 필요가 없는 것 같습니다. 해당 속성을 정확하게 지칭해서 접근해주세요

2020-08-24 06:33 UTC, soheon-lee commented on car/views.py
> +            return JsonResponse({"message": "Not exist the car with the specs"})
에러코드를 입력하지 않으시면 default인 200으로 갑니다. 주의해주세요

2020-08-24 06:50 UTC, orangemush commented on car/views.py
> +from django.shortcuts   import render
넵!!!!!!!!!!!!!!!!

2020-08-24 06:50 UTC, orangemush commented on car/views.py
> +from django.forms.models import model_to_dict
네엡!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11

2020-08-24 06:57 UTC, orangemush commented on car/views.py
> +from .models            import *
네엡!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!22

2020-08-24 07:00 UTC, orangemush commented on car/views.py
> +        #     return JsonResponse({'message': 'VALUE_ERROR'}, status = 400)
물론이죠

2020-08-24 07:00 UTC, orangemush commented on car/views.py
> +            #     wheel_list.append(wheel['inch'])
좋습니다 !!!

2020-08-24 07:03 UTC, orangemush commented on car/views.py
> +            return JsonResponse({"message": "Not exist the car with the specs"})
네엡!!!!!!!

2020-08-24 07:16 UTC, orangemush commented on car/views.py
> +            wheel = wheel[0]['inch'].strip()
네에에에엡!!!!!!!!!!!!!!!!!!!!!!!

2020-08-24 07:20 UTC, orangemush commented on car/views.py
> +            car_specs.warranty = car_specs.warranty.replace('\n\t', "<br>")
해결했습니다 !

2020-08-25 05:16 UTC, evergreen-david requested changes

2020-08-25 05:16 UTC, evergreen-david commented on car/views.py
> +class CarSPageView(View):
```suggestion
class CarPageView(View):
```

2020-08-25 05:16 UTC, evergreen-david commented on car/views.py
> +    CarModel, CarSpecification
```suggestion
    CarModel, 
    CarSpecification
```

2020-08-25 05:16 UTC, evergreen-david commented on car/views.py
> +                'wheel'            : performance_wheel
indent 4칸 주시죠

2020-08-25 09:52 UTC, orangemush commented on car/views.py
> +                'wheel'            : performance_wheel
넵!!!!!!!!!!!!!!!!!!!!!!

2020-08-25 09:53 UTC, orangemush commented on car/views.py
> +    CarModel, CarSpecification
네엡!

2020-08-25 11:53 UTC, orangemush commented on car/views.py
> +class CarSPageView(View):
차량 데이터 배터리 종류마다 데이터 값이 달라져서 그런데 CarSView도 나쁘지 않을까 싶어서 일단 다시 올렸습니다.

2020-08-26 01:29 UTC, lordmyshepherd requested changes

2020-08-26 01:29 UTC, lordmyshepherd commented on car/views.py
> +# 차 모델에 따른 spec들을 보여주는 Endpoint
주석은 제거해주세요~
12, 13, 14

2020-08-26 01:29 UTC, lordmyshepherd commented on car/views.py
> +# http://0:8000/10.58.5.236/car/cyber_page_view (url)
주석 지워주세요~~

2020-08-26 01:29 UTC, lordmyshepherd commented on car/views.py
> +class CyberTruck(View):
완성되지 않은 내용은 지워주세요~

2020-08-26 01:29 UTC, lordmyshepherd commented on car/views.py
> +# http://0:8000/10.58.5.236/car/3_view (url)
주석 지워주세요~

2020-08-26 01:29 UTC, lordmyshepherd commented on car/views.py
> +class CarSView(View):
태기님! 뷰 잘 만들어 주셨습니다~
다만, `CarSView`, `Car3View`, `CyberTruck` 모든 View가 프론트엔드에 전달하는 값이 Car이므로, 하나의 Class로 묶어서 만들어주세요~

또한, urls.py도 RESTful 하게 URI를 표현할 수 있도록 해주세요.
`/cars/<int:car_id>` << 이거 하나로 통일해주세요

2020-08-26 03:37 UTC, orangemush commented on car/views.py
> +class CyberTruck(View):
지웠습니다

2020-08-26 03:37 UTC, orangemush commented on car/views.py
> +# http://0:8000/10.58.5.236/car/3_view (url)
지우겠습니다 !!

2020-08-26 04:31 UTC, orangemush commented on car/views.py
> +class CarSView(View):
네 고쳐보겠습니다 !

2020-08-26 06:55 UTC, lordmyshepherd requested changes

2020-08-26 06:55 UTC, lordmyshepherd commented on car/views.py
> +class CarView(View):
```suggestion
class CarsView(View):
```

2020-08-26 06:55 UTC, lordmyshepherd commented on car/views.py
> +
Car.objects.filter()
car_specs = CarSpecification.objects.filter(car_id = car_id, batter=None)

>>> [{},{},{}]
car_data = {
    "model" : model.name,
   " "
}

2020-08-26 06:55 UTC, lordmyshepherd commented on car/views.py
> +            if car_id == 86:
하드코딩 XXXX!!!!!

2020-08-26 06:55 UTC, lordmyshepherd commented on car/views.py
> +            elif car_id == 87:
하드코딩 XXXX!!!!!

2020-08-26 06:55 UTC, lordmyshepherd commented on car/views.py
> +            elif car_id == 88:
하드코딩 XXXX!!!!!

2020-08-27 08:44 UTC, merged